In [21]:
import numpy as np
from sympy import *
import copy as copy

# Lecture 10 : four fundamental subspaces 

### Space is R^3. One basis as below

In [1]:
basis = [[1, 0, 0],[0, 1, 0], [0, 0, 1]]

In [3]:
another_basis = [[1, 2, 3], [1, 2, 3], [2, 5, 8]]

But the matrix above, an example from last lecture is not actually a basis. While all columns are indepenent, it is not invertible because it has two equal rows. Later in this lecture, we will connect the column space with the row space - the row space of this matrix is only 2D since two of the rows are the same. This in fact means that the rank of the column space is also only 2 - the row space tells us somethign about the column space. 

### Four fundamental subspaces 
#### Columnspace C(A)
#### Nullspace N(A)
#### Rowspace R(A) = C(A^T)

R(A) - all combinations of rows of A. Rows will be a basis for the row space, if all rows are independent. Or, all combinations of the columns of A^T (we prefer column vectors to row vectors). 
So, R(A) = C(A^T)

#### Nullspace of A^T = N(A^T)

N(A^T) is the left nullspace of A


##### If A is m x n:
- C(A) is in R^m
- N(A) is in R^n
- C(A^T) is in R^n
- N(A^T) is in R^m

We want to understand these subspaces: what systematic way will produce their bases? What is their dimension? 

#### Dimension
Dimension of a subspace is its rank.


The dimension of a column space (C(A)) = r of A

A = r

The dimension of a row space (C(A^T)) = r of A, Also!

A^T = r

Row space and column space of a matrix A have the same dimension!

N(A) = n-r  
N(A^T) = m-r

The dimension of the null space plus the dimension of the column space should equal the number of columns  

#### Basis
C(A) - Pivot columms
N(A) - special solutions 
C(A^T) - Pivot columns of A^T
N(A^T) - special solutions 

In [15]:
A =np.array([[1, 2, 3, 1],[1, 1, 2, 1],[1, 2, 3, 1]])

#elimination to get the pivots
rrefA=np.array([[1, 2, 3, 1],[0, 1, 1, 0],[0, 0, 0, 0]])

#clean up the matrix to get R
R=np.array([[1, 0, 1, 1],[0, 1, 1, 0],[0, 0, 0, 0]])
print("The final matrix R has the identity matrix I,\
free variable F, and a row of zeros: ") 
print(R)

#R has the identity matrix 

The final matrix R has the identity matrix I,free variable F, and a row of zeros: 
[[1 0 1 1]
 [0 1 1 0]
 [0 0 0 0]]


But now C(R) =/= C(A)! We did row operations, which should have preserved the rows, and thus C(A^T)=C(R^T) should still apply. But the column space has been altered given that we did row operations. 

##### Basis for row space of A or R is teh first r rows of R
Sometimes it's true for A as well, but not necessarily. 

#### Why is C(A^T)=C(R^T)?
We arrived to R by taking different combinations of the rows of A. So R is certainly in the row sapce of A. Thus the dimension is r, and the natural basis for A is the r rows of R. Reversing the steps of row reductions, we return to the rows of A --> the two row spaces of R and A are the same, and the basis are the same. The natural basis for A is the r rows of R.

#### 4th space: N(A^T)
A^T y = 0  , thus y is in N(A^T).


[ MATRIX ] dot [ COLUMN ] = [ ZERO ] 

(A^T y)^T = y^T A

[y^T][A]=[0]

now y^T is a row

#### How do we get a basis for the left null space? 

Gauss-Jordan: tack on the identity matrix right after A

rref[A mxn I mxm] --> [R mxn E mxm]

And here E will contain a record of what we did to get A to R. 

All that row reduction amountd to multiplying A by E:

[E][A]-->[R]

In chapter 2, R was I, when we were trying to get A-1. Then, E was A-1. 

In [16]:
print(A)

[[1 2 3 1]
 [1 1 2 1]
 [1 2 3 1]]


In [47]:
print("So, following the rref steps we used to get R, repeat for I:")
I=np.identity(3)
print(I)

R=copy.deepcopy(A)
E=copy.deepcopy(I)
E[2]=-I[0]+I[2]
R[2]=-A[0]+A[2]
print(U)

print(".... next .....")
E[1]=I[0]-I[1]
R[1]=A[0]-A[1]
print(U)

print(".... next .....")
E[0]=2*I[1]-I[0]
R[0]=2*A[1]-A[0]
print(R)
print("Matrix E is then =")
print(E)

So, following the rref steps we used to get R, repeat for I:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 1 1]
 [0 1 1 0]
 [0 0 0 0]]
.... next .....
[[1 0 1 1]
 [0 1 1 0]
 [0 0 0 0]]
.... next .....
[[1 0 1 1]
 [0 1 1 0]
 [0 0 0 0]]
Matrix E is then =
[[-1.  2.  0.]
 [ 1. -1.  0.]
 [-1.  0.  1.]]


In [48]:
R==np.dot(E,A)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

The only reason we wanted this blasted E was so that we can figure out the left nullspace. The dimension of the left nullspace is 1: the dimension of A=A^T=r=2. 

Thus, the diemsion of N(A^T):

dN(A^T) = m-r = 3-2 = 1

This means there is 1 combination of the three rows that produces the zero row. The basis for the left nullspace has only 1 vector in it. That vector is in the last row of E: 

In [50]:
E[-1]

array([-1.,  0.,  1.])

Since we're looking at the let nullspace, we are looking for a combiantion of rows to give the zero row.

So to get the basis of the left null space, we have to keep track of E! At least it does not require that transpose the matrix and start all over again. 

### Review

The row space and the null space are in Rn, their dimensions add to n.

The column space and the left null space are in Rm, and their dimensions add to m. 

### A new vector sapce, M

All 3x3 matrices: every 3x3 matrix is our vector in the vector space. 

Our vectors in the vectrorsapce just need to obey the rules of vectorsapces: 
1. We need to be able to add the vectors to get the span of the vectorspace: we can add matrices
2. We need to be able to multiply them by scalars: we can multiply matrices by 7
3. We need to be able to take combinatinos of vectors: we can take 2 of one matrix and add it to 3 of another matrix 
4. We have a 0 matrix
...

All those 8 rules for a vector space are easily satisfied with matrices as well. Since right now we are just intersterd in adding matrics (A+B) and multiplying them by scalars (cA), we are not currently interesred in matrix multiplicaiton (AB).

#### Subspaces of M
- all upper triangular matrices
- all symmetric matrices
- the intersction of two subspaces are another subspace: diagonal matrices (zeros above and below the diagonal). This subspace is smaller than the first two, since this subspace is contained in the first two. 

Next time we will produce the dimension and basis of the exampels above. 

#### Dimensions of the subspaces of M
- Upper triangular matrices
- Symmetric matrices
- Diagonal matrices: d=3 (three independent diagonal matrices)