In [7]:
import numpy as np
from sympy import *

# Lecture 10 : four fundamental subspaces 

### Space is R^3. One basis as below

In [1]:
basis = [[1, 0, 0],[0, 1, 0], [0, 0, 1]]

In [3]:
another_basis = [[1, 2, 3], [1, 2, 3], [2, 5, 8]]

But the matrix above, an example from last lecture is not actually a basis. While all columns are indepenent, it is not invertible because it has two equal rows. Later in this lecture, we will connect the column space with the row space - the row space of this matrix is only 2D since two of the rows are the same. This in fact means that the rank of the column space is also only 2 - the row space tells us somethign about the column space. 

### Four fundamental subspaces 
#### Columnspace C(A)
#### Nullspace N(A)
#### Rowspace R(A) = C(A^T)

R(A) - all combinations of rows of A. Rows will be a basis for the row space, if all rows are independent. Or, all combinations of the columns of A^T (we prefer column vectors to row vectors). 
So, R(A) = C(A^T)

#### Nullspace of A^T = N(A^T)

N(A^T) is the left nullspace of A


##### If A is m x n:
- C(A) is in R^m
- N(A) is in R^n
- C(A^T) is in R^n
- N(A^T) is in R^m

We want to understand these subspaces: what systematic way will produce their bases? What is their dimension? 

#### Dimension
Dimension of a subspace is its rank
The dimension of a column space (C(A)) = r of A
The dimension of a row space (C(A^T)) = r of A, Also!

Row space and column space of a matrix A have the same dimension!

N(A) = n-r  
N(A^T) = m-r

The dimension of the null space plus the dimension of the column space should equal the number of columns  

#### Basis
C(A) - Pivot columms
N(A) - special solutions 
C(A^T) - Pivot columns of A^T
N(A^T) - special solutions 

In [13]:
A =np.array([[1, 2, 3, 1],[1, 1, 2, 1],[1, 2, 3, 1]])

#elimination to get the pivots
A=np.array([[1, 2, 3, 1],[0, 1, 1, 0],[0, 0, 0, 0]])

#clean up the matrix to get R
R=np.array([[1, 0, 1, 1],[0, 1, 1, 0],[0, 0, 0, 0]])
print("The final matrix R has the identity matrix I,\
free variable F, and a row of zeros: ") 
print(R)

#R has the identity matrix 

The final matrix R has the identity matrix I, free variable F, and a row of zeros: 
[[1 0 1 1]
 [0 1 1 0]
 [0 0 0 0]]


But now C(R) =/= C(A)! We did row operations, which should have preserved the rows, and thus C(A^T)=C(R^T) should still apply. But the column space has been altered given that we did row operations. 

##### Basis for row space of A or R is teh first r rows of R
Sometimes it's true for A as well, but not necessarily. 

#### Why is C(A^T)=C(R^T)?
We arrived to R by taking different combinations of the rows of A. So R is certainly in the row sapce of A. Thus the dimension is r, and the natural basis for A is the r rows of R. Reversing the steps of row reductions, we return to the rows of A --> the two row spaces of R and A are the same, and the basis are the same. The natural basis for A is the r rows of R.

#### 4th space: N(A^T)
A^T y = 0  , thus y is in N(A^T).


[ MATRIX ] dot [ COLUMN ] = [ ZERO ] 