In [113]:
%matplotlib inline
from sympy import *
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
from scipy import *
import copy as copy

### Section 2.5, #24

UU^-1 = I 

In [148]:
a, b, c, x1, x2 ,x3 = symbols("a b c x1 x2 x3", real=True)

In [149]:
UI = np.array([[1, a, b, 1, 0, 0],
[0, 1, c, 0, 1, 0],
[0, 0, 1, 0, 0, 1]])

In [150]:
UI_t= copy.deepcopy(UI)

In [151]:
UI_t=UI_t*np.array([[1],[-a],[1]])
UI_t[0] = UI_t[0]+UI_t[1]
UI_t[1]=UI_t[1]/(-a)
UI_t[1]=UI_t[1]+UI_t[2]*(-c)
UI_t[0]=UI_t[0]+UI_t[2]*(a*c-b)
UI_t


array([[1, 0, 0, 1, -a, a*c - b],
       [0, 1, 0, 0, 1, -c],
       [0, 0, 1, 0, 0, 1]], dtype=object)

In [152]:
U_m1=UI_t[:, [3, 4, 5]]
U_m1

array([[1, -a, a*c - b],
       [0, 1, -c],
       [0, 0, 1]], dtype=object)

In [153]:
U=UI[:, [0, 1, 2]]
U

array([[1, a, b],
       [0, 1, c],
       [0, 0, 1]], dtype=object)

In [157]:
U.dot(U_m1)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=object)

### #40

In [126]:
A = np.array([[1, -a, 0, 0], 
     [0, 1, -b, 0], 
     [0, 0, 1, -c], 
     [0, 0, 0, 1]])

In [127]:
AI = np.array([[1, -a, 0, 0, 1, 0, 0, 0], 
     [0, 1, -b, 0, 0, 1, 0, 0], 
     [0, 0, 1, -c, 0, 0, 1, 0], 
     [0, 0, 0, 1, 0, 0, 0, 1,]])

In [128]:
Am1= copy.deepcopy(AI)
Am1[2] = AI[3]*c+AI[2]
Am1

array([[1, -a, 0, 0, 1, 0, 0, 0],
       [0, 1, -b, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, c],
       [0, 0, 0, 1, 0, 0, 0, 1]], dtype=object)

In [129]:
Am1[1] = Am1[2]*b+Am1[1]
Am1

array([[1, -a, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, b, b*c],
       [0, 0, 1, 0, 0, 0, 1, c],
       [0, 0, 0, 1, 0, 0, 0, 1]], dtype=object)

In [130]:
Am1[0] = Am1[1]*a+Am1[0]
Am1

array([[1, 0, 0, 0, 1, a, a*b, a*b*c],
       [0, 1, 0, 0, 0, 1, b, b*c],
       [0, 0, 1, 0, 0, 0, 1, c],
       [0, 0, 0, 1, 0, 0, 0, 1]], dtype=object)

In [131]:
Am1=Am1[:, [4, 5, 6, 7]]
Am1

array([[1, a, a*b, a*b*c],
       [0, 1, b, b*c],
       [0, 0, 1, c],
       [0, 0, 0, 1]], dtype=object)

In [132]:
np.dot(A, Am1)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=object)

### Section 2.6, #13

In [93]:
a, b, c, d, x, l = symbols("a b c d x l", real=True)

In [114]:
A = np.array([
             [a, a, a, a],
             [a, b, b, b],
             [a, b, c, c],
             [a, b, c, d]])

Find L, U such that A = LU

In [115]:
L = np.array([
             [l, 0, 0, 0],
             [l, l, 0, 0],
             [l, l, l, 0],
             [l, l, l, l]])

In [116]:
U = copy.deepcopy(A)
U[3]=A[3]-A[2]
U[2]=A[2]-A[1]
U[1]=A[1]-A[0]
U

array([[a, a, a, a],
       [0, -a + b, -a + b, -a + b],
       [0, 0, -b + c, -b + c],
       [0, 0, 0, -c + d]], dtype=object)

In [124]:
L = np.array([
             [1, 0, 0, 0],
             [1, 1, 0, 0],
             [1, 1, 1, 0],
             [1, 1, 1, 1]])

In [125]:
LU=np.dot(L,U)
LU

array([[a, a, a, a],
       [a, b, b, b],
       [a, b, c, c],
       [a, b, c, d]], dtype=object)

In [119]:
A==LU

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### #26

In [202]:
K7m1 = np.zeros((6,6))
K7m1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [203]:
K7m1[0]=[6, 5, 4, 3, 2, 1]
K7m1[:,[0]]= [[6], [5], [4], [3], [2], [1]]
K7m1

array([[6., 5., 4., 3., 2., 1.],
       [5., 0., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [204]:
for i in range(1, len(K7m1)):
    K7m1[i][i:]=(i+1)*K7m1[0][i:]
    K7m1[(i+1):,i]=(i+1)*K7m1[(i+1):,0]
    
print(K7m1)

[[ 6.  5.  4.  3.  2.  1.]
 [ 5. 10.  8.  6.  4.  2.]
 [ 4.  8. 12.  9.  6.  3.]
 [ 3.  6.  9. 12.  8.  4.]
 [ 2.  4.  6.  8. 10.  5.]
 [ 1.  2.  3.  4.  5.  6.]]


In [205]:
Km1=(1/7)*(K7m1)

In [208]:
K=np.linalg.inv(Km1)
K

array([[ 2.00000000e+00, -1.00000000e+00, -1.85037171e-17,
         1.11022302e-16,  9.25185854e-18, -9.25185854e-18],
       [-1.00000000e+00,  2.00000000e+00, -1.00000000e+00,
        -1.33226763e-16,  6.66133815e-17,  4.44089210e-17],
       [ 1.89663100e-16, -1.00000000e+00,  2.00000000e+00,
        -1.00000000e+00,  0.00000000e+00, -2.77555756e-17],
       [-1.29526020e-16, -0.00000000e+00, -1.00000000e+00,
         2.00000000e+00, -1.00000000e+00,  0.00000000e+00],
       [ 9.25185854e-17,  0.00000000e+00,  1.38777878e-17,
        -1.00000000e+00,  2.00000000e+00, -1.00000000e+00],
       [-1.85037171e-17,  0.00000000e+00, -2.77555756e-17,
         0.00000000e+00, -1.00000000e+00,  2.00000000e+00]])

In [209]:
np.dot(K,K7m1)

array([[ 7.00000000e+00, -1.77635684e-15,  0.00000000e+00,
         0.00000000e+00,  4.44089210e-16,  2.22044605e-16],
       [ 0.00000000e+00,  7.00000000e+00, -3.55271368e-15,
        -1.77635684e-15,  0.00000000e+00,  0.00000000e+00],
       [ 1.77635684e-15,  0.00000000e+00,  7.00000000e+00,
         0.00000000e+00,  1.77635684e-15,  8.88178420e-16],
       [-8.88178420e-16,  0.00000000e+00,  0.00000000e+00,
         7.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.10622664e-16,  5.73615229e-16,  5.36607795e-16,
         4.02455846e-16,  7.00000000e+00, -1.64220489e-15],
       [-2.22044605e-16, -3.14563190e-16, -4.07081776e-16,
        -3.05311332e-16, -2.03540888e-16,  7.00000000e+00]])

### Section 2.7, #13